apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: n8n-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "4cc1d091-0fd0-411b-b400-6cbc1e9171b1"
    keyvaultName: "kv-gee-n8n"
    tenantId: "4183e53a-54a1-4dc5-bcb5-1a64a6fff3af"
    objects: |
      array:
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: db-host
          objectType: secret
        - |
          objectName: db-port
          objectType: secret
  secretObjects:
    - secretName: n8n-container-env
      type: Opaque
      data:
        - objectName: db-user
          key: DB_POSTGRESDB_USER
        - objectName: db-password
          key: DB_POSTGRESDB_PASSWORD
        - objectName: db-host
          key: DB_POSTGRESDB_HOST
        - objectName: db-port
          key: DB_POSTGRESDB_PORT
