apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: n8n-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "8fffcdf6-d232-4faa-be30-6d62fdef31a9"
    keyvaultName: "kv-n8n"
    tenantId: "6c0d1498-a808-4d41-a865-fdebeb412738"
    objects: |
      array:
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: db-host
          objectType: secret
        - |
          objectName: db-port
          objectType: secret
  secretObjects:
    - secretName: n8n-container-env
      type: Opaque
      data:
        - objectName: db-user
          key: DB_POSTGRESDB_USER
        - objectName: db-password
          key: DB_POSTGRESDB_PASSWORD
        - objectName: db-host
          key: DB_POSTGRESDB_HOST
        - objectName: db-port
          key: DB_POSTGRESDB_PORT
